title: Currículo - Ivo Marcelo Leonardi Zaniolo
url: 'http://imarcelolz.github.io'
#baseurl: '/' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Ivo Marcelo Leonardi Zaniolo
tagline: Desenvolvedor <br/> Front e Back End </br> &amp; Empreendedor
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: imarcelolz@gmail.com
phone: +55 (71) 993-023-400
website: blog.webjeda.com #do not add http://
linkedin: imarcelolz
github: imarcelolz
twitter: '@imarcelolz'

#Update all the sections by editing the files inside _includes folder.
